name: Golf Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # every day at 4 AM UTC

jobs:
  pull-and-insert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SPORTSDATA_API_KEY: ${{ secrets.SPORTSDATA_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py
